### ISSUE TITLE
Cannot GET /endpoint/gpt

### ISSUE THREAD

**Issue by 35develr** [roblandry/localai-nodered#1]
i tried your integration

when i call the service "conversation" i get the following error:

 Logger: custom_components.nodered_conversation
Source: custom_components/nodered_conversation/__init__.py:106
Integration: NodeRed Conversation
First occurred: 14:32:48 (3 occurrences)
Last logged: 14:37:32
Something happened: Expecting value: line 1 column 1 (char 0)

LocalAi is running at http://10.x.x.xxx:8080/v1
But i see no config Option to set the LocalAI Endpoint in your example flow.

when i set the endpoint uri to GET i can Access it in Browser, for testing with Homeassistant i set it to POST

Please help ;-)

**Comment by roblandry** [comment]
To see what url you set check your .storage/core.config_entries.

Your config should be similar to this:
```json
{
        "entry_id": "b8f81a2ac0e31471cf9be78dc29bba1c",
        "version": 1,
        "domain": "nodered_conversation",
        "title": "NodeRed Conversation",
        "data": {
          "nodered_url": "https://10.0.1.1:1880/endpoint/gpt",
          "nodered_user": "nodeuser",
          "nodered_pass": "nodepass"
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": null,
        "disabled_by": null
      },
```

The integration config option points to nodered. The nodered nodes point to open/localai.

**Comment by roblandry** [comment]
With no response I'm going to assume it's working and close the issue
